apiVersion: v1
kind: Secret
metadata:
  name: echo-secret
  namespace: default
type: Opaque
data:
  # Base64 encoded values
  JWT_SECRET: "M2M5ZTRlMmQ0YTJmNGMzZThlN2I2ZDVjNGEzYjJhMWE2ZjVlNGQzYzJiMWEwZjllOGQ3YzZiNWE0ZjNlMmQxYw=="
  POSTGRES_PASSWORD: "ZWNob19wYXNz"
  ECHO_AES_KEY: "YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY="
