server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      routes:
        - id: user-service-auth
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
        - id: user-service-users
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - JwtValidationFilter
        - id: chat-service-groups
          uri: lb://chat-service
          predicates:
            - Path=/api/groups/**
          filters:
            - JwtValidationFilter
        - id: message-store-service-history
          uri: lb://message-store-service
          predicates:
            - Path=/api/messages/**
          filters:
            - JwtValidationFilter
        - id: chat-service-ws
          uri: lb:ws://chat-service
          predicates:
            - Path=/ws/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

# Secret key matching user-service for JWT verification (HS256 requires at least 256 bits, i.e., 32 characters)
app:
  jwt:
    secret: "3c9e4e2d4a2f4c3e8e7b6d5c4a3b2a1a6f5e4d3c2b1a0f9e8d7c6b5a4f3e2d1c"
